name: Android Tests

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    - name: Start emulator
      run: |
        echo "no" | avdmanager create avd --force --name test --abi google_apis/x86_64 --package 'system-images;android-30;google_apis;x86_64'
        emulator -avd test -no-window -no-audio -no-boot-anim -no-snapshot -camera-back none -camera-front none -selinux permissive -qemu -m 2048 &

    - name: Wait for emulator to start
      run: |
        android-wait-for-emulator

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run connectedAndroidTest
      run: ./gradlew connectedAndroidTest
